---
title: "Untitled"
author: "Zain Asaf"
date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}

library(tidyverse)
library(ggplot2)
```



```{r}

head(scotland)
head(england_wales)


## Household deprivaion not included i Scotland dta
## Natioanl identity difrent categoreis - not comparbale betweeen the two 
## Household/family type not asked in scotland

# Define rename mapping from England & Wales to Scotland
rename_vector <- c(
  "Female" = "sex__female",
  "Male" = "sex__male",
  "Aged_4_years_and_under" = "age__0_15",
  "Aged_5_to_9_years" = "age__0_15",
  "Aged_10_to_14_years" = "age__0_15",
  "Aged_15_to_19_years" = "age__16_24",
  "Aged_20_to_24_years" = "age__16_24",
  "Aged_25_to_29_years" = "age__25_34",
  "Aged_30_to_34_years" = "age__25_34",
  "Aged_35_to_39_years" = "age__35_49",
  "Aged_40_to_44_years" = "age__35_49",
  "Aged_45_to_49_years" = "age__35_49",
  "Aged_50_to_54_years" = "age__50_64",
  "Aged_55_to_59_years" = "age__50_64",
  "Aged_60_to_64_years" = "age__50_64",
  "Aged_65_to_69_years" = "age__65_and_over",
  "Aged_70_to_74_years" = "age__65_and_over",
  "Aged_75_to_79_years" = "age__65_and_over",
  "Aged_80_to_84_years" = "age__65_and_over",
  "Aged_85_years_and_over" = "age__65_and_over",
  "No_qualifications" = "qualification__no_qualifications",
  "Level_1_and_entry_level_qualifications" = "qualification__level_1_or_2",
  "Level_2_qualifications" = "qualification__level_1_or_2",
  "Level_3_qualifications" = "qualification__level_3",
  "Level_4_qualifications_or_above" = "qualification__level_4_and_above",
  "Other_qualifications" = "qualification__other",
  
  # Economic Activity
  "Economically_active_(excluding_full_time_students)_In_employment_Employee_Full_time" = "economic_activity__full_time",
  "Economically_inactive_Other" = "economic_activity__other_inactive", 
  "Economically_active_(excluding_full_time_students)_In_employment_Employee_Part_time" = "economic_activity__part_time",
  "Economically_active_(excluding_full_time_students)_In_employment_Self_employed_with_employees" = "economic_activity__self_employed",
  "Economically_active_(excluding_full_time_students)_Unemployed" = "economic_activity__unemployed",
  "Economically_active_and_a_full_time_student_Unemployed" = "economic_activity_unemployed",
  "Full_time_student" = "economic_activity__student",
  "Economically_inactive_Retired" = "economic_activity__retired",
  "Economically_inactive_Student" = "economic_activity__student",
  "Economically_inactive_Looking_after_home_or_family" = "economic_activity__looking_after_home_or_family",               
  "Economically_inactive_Long_term_sick_or_disabled" = "economic_activity__long_term_sick_or_disabled",
  "Economically_inactive_Other" = "economic_activity__other_economically_inactive",
  
  # Ethnicity
  "White" = "ethnicity__white",
  "Mixed_or_Multiple_ethnic_groups" = "ethnicity__mixed",
  "Asian_Asian_British_or_Asian_Welsh" = "ethnicity__asian",
  "Black_or_Black_British_Welsh_Carribean_or_African" = "ethnicity__black",
  "Other_ethnic_group" = "ethnicity__other",

  # Tenure
  "Owned_Owns_outright" = "tenure__owned_outrght",
  "Owned_Owns_with_a_mortgage_or_loan" = "tenure__owned_with_mortgage",
  "Shared_ownership" = "tenure__shared_equity",
  "Social_rented" = "tenure__social_rented",
  "Private_rented" = "tenure__private_rented",
  "Lives_rent_free" = "tenure__rent_free",

  # Health
  "Good_health" = "health_status__good",
  "Fair_health" = "health_status__fair",
  "Bad_health" = "health_status__bad",

  # Religion
  "No_religion" = "religion__no_religion",
  "Christian" = "religion__catholic_or_other_christian",
  "Buddhist" = "religion__other",
  "Hindu" = "religion__other",
  "Jewish" = "religion__other",
  "Muslim" = "religion__muslim",
  "Sikh" = "religion__other",
  "Other_religion" = "religion__other",
  "Not_answered" = "religion__not_stated",

  # Disability
  "Disability_Limited_A_Lot" = "disability__limited_a_lot",
  "Disability_Limited_A_Little" = "disability__limited_a_little",
  "Disability_Not_Limited" = "disability__not_limited",

  # Occupations 
  "1_Managers_directors_and_senior_officials" = "occupation__manager_director_senior_official", 
  "2_Professional_occupations" = "occupation__professional",                                          
  "3_Associate_professional_and_technical_occupations" = "occupation__associate_professional_technical",                                          
  "4_Administrative_and_secretarial_occupations" = "occupation__administrative_secretarial",       
  "5_Skilled_trades_occupations" = "occupation__skilled_trade",                                           
  "6_Caring_leisure_and_other_service_occupations" = "occupation__caring_leisure_service",                
  "7_Sales_and_customer_service_occupations" = "occupation__sales_customer_service",                      
  "8_Process_plant_and_machine_operatives" = "occupation__process_plant_machine_operative",              
  "9_Elementary_occupations" = "occupation__elementary_occupations",

  # Marital Status
  "Never_married_and_never_registered_a_civil_partnership" = "marital_status__never_married",
  "Married_or_in_a_registered_civil_partnership_In_a_registered_civil_partnership_Opposite_sex" = "marital_status__married",    
  "Married_or_in_a_registered_civil_partnership_In_a_registered_civil_partnership_Same_sex" = "marital_status__married",
  "Married_or_in_a_registered_civil_partnership_Married_Opposite_sex" = "marital_status__married",  
  "Married_or_in_a_registered_civil_partnership_Married_Same_sex" = "marital_status__married",
  "Widowed_or_surviving_civil_partnership_partner" = "marital_status__widowed",
  "Divorced_or_civil_partnership_dissolved" = "marital_status__divorced"
)



england_wales <- read.csv("data/merged_df_england_wales.csv")

# Check for column names that match the rename vector
matching_columns <- colnames(england_wales) %in% names(rename_vector)
print(matching_columns)

# Rename columns using the rename vector
england_wales_renamed <- england_wales %>%
  rename_at(vars(one_of(names(rename_vector))), ~ rename_vector[.])

# Verify renamed columns
print(colnames(england_wales_renamed))








existing_columns <- colnames(england_wales)

# Find any column names in rename_vector that are missing
missing_columns <- setdiff(names(rename_vector), existing_columns)

# Print missing column names
if (length(missing_columns) > 0) {
  message("The following columns are missing from england_wales and won't be renamed: ", paste(missing_columns, collapse = ", "))
}



# Apply renaming only for existing columns
rename_vector <- rename_vector[names(rename_vector) %in% existing_columns]

# Apply renaming
england_wales <- england_wales %>%
  rename(!!!rename_vector)  

# Check renamed column names
colnames(england_wales)

sort(names(england_wales))


```


```{r}



# Group by summarise mean

data_joined <- full_join(
 
  england_wales %>%
    group_by(segment) %>%
    summarise(across(where(is.numeric), mean, na.rm = TRUE)),

  scotland %>%
    group_by(segment) %>%
    summarise(across(where(is.numeric), mean, na.rm = TRUE)),
 
  by="segment")

# Then get difference

data_joined %>%
  select(segment,Female,sex__female) %>%
  mutate(difference = Female-sex__female)



